server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bookservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/books/**
        - id: employeeservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/employees/**
        - id: borrowservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/borrows/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
